ViewModels/DashboardViewModel.cs
using FindWorkApp.Models;

namespace FindWorkApp.ViewModels
{
    public class DashboardViewModel
    {
        public List<JobResume> Resumes { get; set; }
        public List<Vacancy> Vacancies { get; set; }
    }
}

Controllers/DashboardController.cs
using FindWorkApp.Data;
using FindWorkApp.Interfaces;
using FindWorkApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FindWorkApp.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardRepository _dashboardRepository;

        public DashboardController(IDashboardRepository dashboardRepository)
        {
            _dashboardRepository = dashboardRepository;
        }

        public async Task<IActionResult> Dashboard()
        {
            var userJobResymes = await _dashboardRepository.GetAllUserJobResume();
            var userVacancies = await _dashboardRepository.GetAllUserVacancy();
            var dashboardViewModel = new DashboardViewModel()
            {
                Resumes = userJobResymes,
                Vacancies = userVacancies,
            };
            return View(dashboardViewModel);
        }
    }
}

Controllers/JobResumeController.cs
using FindWorkApp.Data;
using FindWorkApp.Interfaces;
using FindWorkApp.Models;
using FindWorkApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace FindWorkApp.Controllers
{
    public class JobResumeController : Controller
    {
        private readonly IJobResumeRepository _jobResumeRepository;
        private readonly IHttpContextAccessor _httpContextAccessor; 

        public JobResumeController(IJobResumeRepository jobResumeRepository, IHttpContextAccessor httpContextAccessor)
        {
            _jobResumeRepository = jobResumeRepository; 
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Работодателям()
        {
            // вернем вакансию из бд
            IEnumerable<JobResume> jobResumes = await _jobResumeRepository.GetAll();
            return View(jobResumes);
        }

        public async Task<IActionResult> JobResumeDetail(int id) // получаем id
        {
            JobResume resume = await _jobResumeRepository.GetByIdAsync(id);
            return View(resume);
        }

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createJobResumeViewModel = new CreateJobResumeViewModel { AppUserId = curUserId };
            return View(createJobResumeViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateJobResumeViewModel resumeVM)
        {
            if (ModelState.IsValid) 
            {
                DateTime currentDate = DateTime.Now;
                CultureInfo russianCulture = new CultureInfo("ru-RU");
                string formattedDate = currentDate.ToString("d MMMM yyyy", russianCulture);
                var jobResume = new JobResume
                {
                    CareerObjective = resumeVM.CareerObjective,
                    WorkExpirience = resumeVM.WorkExpirience,
                    Salary = resumeVM.Salary,
                    AppUserId = resumeVM.AppUserId,
                    Email = resumeVM.Email,
                    Age = resumeVM.Age,
                    Date = formattedDate,
                    FullName = resumeVM.FullName,
                    Gender = resumeVM.Gender,
                    PhoneNumber = resumeVM.PhoneNumber,
                    Education = resumeVM.Education,
                    Description = resumeVM.Description,
                    Image = resumeVM.Image,
                    Address = new Address
                    {
                        City = resumeVM.Address.City,
                    }
                };
                _jobResumeRepository.Add(jobResume);
                return RedirectToAction("Dashboard", "Dashboard");
            }
            return View(resumeVM);
            
        }

        public async Task<IActionResult> Edit(int id)
        {
            DateTime currentDate = DateTime.Now;
            CultureInfo russianCulture = new CultureInfo("ru-RU");
            string formattedDate = currentDate.ToString("d MMMM yyyy", russianCulture);
            var jobResume = await _jobResumeRepository.GetByIdAsync(id);
            if (jobResume == null) return View("Error");
            var jobResumeVM = new EditJobResumeViewModel
            {
                CareerObjective = jobResume.CareerObjective,
                WorkExpirience = jobResume.WorkExpirience,
                AddressId = jobResume.AddressId,
                Salary = jobResume.Salary,
                Age = jobResume.Age,
                Email = jobResume.Email,
                Date = formattedDate,
                AppUserId = jobResume.AppUserId,
                FullName = jobResume.FullName,
                Gender = jobResume.Gender,
                PhoneNumber = jobResume.PhoneNumber,
                Education = jobResume.Education,
                Description = jobResume.Description,
                Image = jobResume.Image,
                Address = new Address
                {
                    City = jobResume.Address.City,
                }
            };
            return View(jobResumeVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditJobResumeViewModel jobResumeVM)
        {
            DateTime currentDate = DateTime.Now;
            CultureInfo russianCulture = new CultureInfo("ru-RU");
            string formattedDate = currentDate.ToString("d MMMM yyyy", russianCulture);
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Ошибка в редактировании резюме");
                return View("Edit", jobResumeVM);
            }
            var userJobResume = await _jobResumeRepository.GetByIdAsyncNoTracking(id);
            if (userJobResume != null)
            {
                var jobResume = new JobResume
                {
                    Id = jobResumeVM.Id,
                    CareerObjective = jobResumeVM.CareerObjective,
                    WorkExpirience = jobResumeVM.WorkExpirience,
                    Salary = jobResumeVM.Salary,
                    Age = jobResumeVM.Age,
                    Date = formattedDate,
                    AppUserId = jobResumeVM.AppUserId,
                    FullName = jobResumeVM.FullName,
                    Email = jobResumeVM.Email,
                    Gender = jobResumeVM.Gender,
                    PhoneNumber = jobResumeVM.PhoneNumber,
                    Education = jobResumeVM.Education,
                    Description = jobResumeVM.Description,
                    Image = jobResumeVM.Image,
                    Address = new Address
                    {
                        City = jobResumeVM.Address.City,
                    }

                };
                _jobResumeRepository.Update(jobResume);
                return RedirectToAction("Dashboard", "Dashboard");
            }
            else return View(jobResumeVM);
            
           
        }

        public async Task<IActionResult> Delete(int id)
        {
            var resumeDetail = await _jobResumeRepository.GetByIdAsync(id);
            if (resumeDetail == null) return View("Error");
            return View(resumeDetail);
;       }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteJobResume(int id)
        {
            var resumeDetail = await _jobResumeRepository.GetByIdAsync(id);
            if (resumeDetail == null) return View("Error");
            _jobResumeRepository.Delete(resumeDetail);
            return RedirectToAction("Dashboard", "Dashboard");
        }
    }
}

Controllers/VacancyController.cs
using FindWorkApp.Data;
using FindWorkApp.Interfaces;
using FindWorkApp.Models;
using FindWorkApp.Repository;
using FindWorkApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace FindWorkApp.Controllers
{
    public class VacancyController : Controller
    {
        private readonly IVacancyRepository _vacancyRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public VacancyController(IVacancyRepository vacancyRepository, IHttpContextAccessor httpContextAccessor)
        {
            _vacancyRepository = vacancyRepository;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Соискателям()
        {
            IEnumerable<Vacancy> vacancies = await _vacancyRepository.GetAll();
            return View(vacancies);
        }

        public async Task<IActionResult> VacancyDetail(int id) // получаем id
        {
            Vacancy vacancy = await _vacancyRepository.GetByIdAsync(id);
            return View(vacancy);
        }

        public IActionResult Create()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            var createVacancyViewModel = new CreateVacancyViewModel { AppUserId = curUserId };
            return View(createVacancyViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateVacancyViewModel vacancyVM)
        {
            if (ModelState.IsValid)
            {
                DateTime currentDate = DateTime.Now;
                CultureInfo russianCulture = new CultureInfo("ru-RU");
                string formattedDate = currentDate.ToString("d MMMM yyyy", russianCulture);
                var vacancy = new Vacancy
                {
                    WorkExpirienceAge = vacancyVM.WorkExpirienceAge,
                    Salary = vacancyVM.Salary,
                    ProgrammingLanguage = vacancyVM.ProgrammingLanguage,
                    Description = vacancyVM.Description,
                    Image = vacancyVM.Image,
                    Email = vacancyVM.Email,
                    DistanceWork = vacancyVM.DistanceWork,
                    CompanyInfo = vacancyVM.CompanyInfo,
                    Date = formattedDate,
                    AppUserId = vacancyVM.AppUserId,
                    AddressId = vacancyVM.AddressId,
                    Address = new Address
                    {
                        City = vacancyVM.Address.City,
                    }
                };
                _vacancyRepository.Add(vacancy);
                return RedirectToAction("Dashboard", "Dashboard");
            }
            return View(vacancyVM);
        }


        public async Task<IActionResult> Edit(int id)
        {
            DateTime currentDate = DateTime.Now;
            CultureInfo russianCulture = new CultureInfo("ru-RU");
            string formattedDate = currentDate.ToString("d MMMM yyyy", russianCulture);
            var vacancy = await _vacancyRepository.GetByIdAsync(id);
            if (vacancy == null) return View("Error");
            var vacancyVM = new EditVacancyViewModel
            {
                WorkExpirienceAge = vacancy.WorkExpirienceAge,
                Salary = vacancy.Salary,
                ProgrammingLanguage = vacancy.ProgrammingLanguage,
                AppUserId = vacancy.AppUserId,
                Date = formattedDate,
                Description = vacancy.Description,
                Image = vacancy.Image,
                Email = vacancy.Email,
                DistanceWork = vacancy.DistanceWork,
                CompanyInfo = vacancy.CompanyInfo,
                AddressId = vacancy.AddressId,
                Address = new Address
                {
                    City = vacancy.Address.City,
                }


            };
            return View(vacancyVM);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditVacancyViewModel vacancyVM)
        {
            DateTime currentDate = DateTime.Now;
            CultureInfo russianCulture = new CultureInfo("ru-RU");
            string formattedDate = currentDate.ToString("d MMMM yyyy", russianCulture);
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Ошибка в редактировании вакансии");
                return View("Edit", vacancyVM);
            }
            var userVacancy = await _vacancyRepository.GetByIdAsyncNoTracking(id);
            if (userVacancy != null)
            {
                var vacancy = new Vacancy
                {
                    Id = vacancyVM.Id,
                    WorkExpirienceAge = vacancyVM.WorkExpirienceAge,
                    Salary = vacancyVM.Salary,
                    Date = formattedDate,
                    ProgrammingLanguage = vacancyVM.ProgrammingLanguage,
                    Description = vacancyVM.Description,
                    AppUserId = vacancyVM.AppUserId,
                    DistanceWork = vacancyVM.DistanceWork,
                    CompanyInfo = vacancyVM.CompanyInfo,
                    Image = vacancyVM.Image,
                    Email = vacancyVM.Email,
                    AddressId = vacancyVM.AddressId,
                    Address = new Address
                    {
                        City = vacancyVM.Address.City,
                    }
                };
                _vacancyRepository.Update(vacancy);
                return RedirectToAction("Dashboard", "Dashboard");
            }
            else return View(vacancyVM);
        }


        public async Task<IActionResult> Delete(int id)
        {
            var vacancyDetail = await _vacancyRepository.GetByIdAsync(id);
            if (vacancyDetail == null) return View("Error");
            return View(vacancyDetail);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteVacancy(int id)
        {
            var vacancyDetail = await _vacancyRepository.GetByIdAsync(id);
            if (vacancyDetail == null) return View("Error");
            _vacancyRepository.Delete(vacancyDetail);
            return RedirectToAction("Dashboard", "Dashboard");
        }
    }
}

Views/Dashboard/Dashboard.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager

@model FindWorkApp.ViewModels.DashboardViewModel
<style>
    body::before {
        content: "";
        position: fixed;
        top: 350px;
        left: 660px;
        width: 100%;
        height: 100%;
        background: url('@Url.Content("~/photo/VacancyDetail.jpg")');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center right; /* Сдвигаем вправо */
        z-index: -1;
        filter: blur(0px);
        transform: scale(2); /* Увеличиваем масштаб */
    }

    body {
        background: #77acf1;
        color: #000000;
        overflow-x: hidden;
    }

    .bold-text {
        font-weight: bold;
    }
</style>
<div class="text-center mb-4">
        <a type="button" class="btn btn-outline-primary btn-lg" asp-area="" asp-controller="JobResume" asp-action="Create">Создать резюме</a>
        <a type="button" class="btn btn-outline-primary btn-lg" asp-area="" asp-controller="Vacancy" asp-action="Create">Создать Вакансию</a>
        @*<a type="button" class="btn btn-outline-primary btn-lg" asp-area="" asp-controller="Dashboard" asp-action="EditUserProfile">Редактировать профиль</a>*@
    </div>

</div>
<div class="container">
    <div class="container text-center">
        <h2 class="display-2 fw-bold mb-4">Ваши вакансии</h2>
    </div>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        @foreach (var item in Model.Vacancies)
        {
            <div class="col-md-4">
                <div class="card mb-2 box-shadow">
                    <a href="@Url.Action("VacancyDetail", "Vacancy", new { id = item.Id })">
                        <img class="card-img-top" src="@item.Image" width="420" height="330" alt="Card image cap">
                    </a>
                    <div class="card-body">
                        <p class="card-text text-center bold-text">Разработчик на @item.ProgrammingLanguage</p>
                        <p class="card-text">@item.Description</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a type="btn btn-success" asp-controller="Vacancy" asp-action="VacancyDetail" asp-route-id="@item.Id"
                               class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <a asp-controller="Vacancy" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                    <a asp-controller="Vacancy" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Удалить</a>
                                }
                            </div>
                            <small class="text-muted">@item.Date</small>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="container text-center">
        <h2 class="display-2 fw-bold mb-4">Ваши резюме</h2>
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        @foreach (var item in Model.Resumes)
        {
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <a href="@Url.Action("JobResumeDetail", "JobResume", new { id = item.Id })">
                        <img class="card-img-top" src="@item.Image" width="420" height="330" alt="Card image cap">
                    </a>
                    <div class="card-body">
                        <p class="card-text text-center bold-text">@item.CareerObjective</p>
                        <p class="card-text">@item.Description</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a type="btn btn-success" asp-controller="JobResume" asp-action="JobResumeDetail" asp-route-id="@item.Id"
                               class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <a asp-controller="JobResume" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                                    <a asp-controller="JobResume" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Удалить</a>
                                }
                            </div>
                            <small class="text-muted">@item.Date</small>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>